services:
  postgres:
    image: postgres:15.3-alpine
    container_name: b2b_store_ars
    restart: unless-stopped    
    ports:
      - "5432:5432"
    env_file: ./ars-backend/.env.production  
    volumes:
      - app-db-data:/var/lib/postgresql/data:cached
    networks:
      - medusa-network  

  redis:
    image: redis:7.2-alpine
    container_name: redis_b2b
    ports:
      - "6379:6379"    
    restart: unless-stopped
    networks:
      - medusa-network
      
volumes:
  app-db-data:

networks:
  medusa-network:
    driver: bridge  
    